omnirobot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  wheel_front_joint_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_front_joint
    pid: {p: 1.0, i: 1.0, d: 1.0}