omnirobot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  wheel_front_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_front_joint
    pid: {p: 0.4, i: 12, d: 0}
  
  wheel_left_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_left_joint
    pid: {p: 0.4, i: 12, d: 0}

  wheel_right_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_right_joint
    pid: {p: 0.4, i: 12, d: 0}